export const VALIDATION_ERROR_CODES = {
  INVALID_QUERY: 'INVALID_QUERY',
  INVALID_FILTER: 'INVALID_FILTER',
  INVALID_SORT: 'INVALID_SORT',
  INVALID_PAGINATION: 'INVALID_PAGINATION',
  INVALID_FIELD_SELECTION: 'INVALID_FIELD_SELECTION',
  INVALID_BODY: 'INVALID_BODY',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  INVALID_FORMAT: 'INVALID_FORMAT',
} as const

export const RESOURCE_ERROR_CODES = {
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  ENDPOINT_NOT_FOUND: 'ENDPOINT_NOT_FOUND',
} as const

export const BUSINESS_ERROR_CODES = {
  UNSUPPORTED_OPERATION: 'UNSUPPORTED_OPERATION',
  INVALID_STATE: 'INVALID_STATE',
  CONFLICT: 'CONFLICT',
} as const

export const AUTH_ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  EXPIRED_TOKEN: 'EXPIRED_TOKEN',
} as const

export const RATE_LIMIT_ERROR_CODES = {
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  SEARCH_RATE_LIMIT_EXCEEDED: 'SEARCH_RATE_LIMIT_EXCEEDED',
} as const

export const SERVER_ERROR_CODES = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DEPENDENCY_FAILURE: 'DEPENDENCY_FAILURE',
  DATABASE_ERROR: 'DATABASE_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const

export const ERROR_CODES = {
  ...VALIDATION_ERROR_CODES,
  ...RESOURCE_ERROR_CODES,
  ...BUSINESS_ERROR_CODES,
  ...AUTH_ERROR_CODES,
  ...RATE_LIMIT_ERROR_CODES,
  ...SERVER_ERROR_CODES,
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]

export const ERROR_CODE_TO_HTTP_STATUS: Record<ErrorCode, number> = {
  [ERROR_CODES.INVALID_QUERY]: 400,
  [ERROR_CODES.INVALID_FILTER]: 400,
  [ERROR_CODES.INVALID_SORT]: 400,
  [ERROR_CODES.INVALID_PAGINATION]: 400,
  [ERROR_CODES.INVALID_FIELD_SELECTION]: 400,
  [ERROR_CODES.INVALID_BODY]: 400,
  [ERROR_CODES.MISSING_REQUIRED_FIELD]: 400,
  [ERROR_CODES.INVALID_FORMAT]: 400,
  [ERROR_CODES.RESOURCE_NOT_FOUND]: 404,
  [ERROR_CODES.ENDPOINT_NOT_FOUND]: 404,
  [ERROR_CODES.UNSUPPORTED_OPERATION]: 422,
  [ERROR_CODES.INVALID_STATE]: 422,
  [ERROR_CODES.CONFLICT]: 422,
  [ERROR_CODES.UNAUTHORIZED]: 401,
  [ERROR_CODES.INVALID_TOKEN]: 401,
  [ERROR_CODES.EXPIRED_TOKEN]: 401,
  [ERROR_CODES.FORBIDDEN]: 403,
  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: 429,
  [ERROR_CODES.SEARCH_RATE_LIMIT_EXCEEDED]: 429,
  [ERROR_CODES.INTERNAL_ERROR]: 500,
  [ERROR_CODES.DEPENDENCY_FAILURE]: 500,
  [ERROR_CODES.DATABASE_ERROR]: 500,
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 503,
}
